
const trial_info = [

    {
            picture: "images/13_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 13,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/13_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 13,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/13_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 13,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/13_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 13,
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/14_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 14,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/14_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 14,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/14_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 14,
            expected: "same",
            angle: 150
        },
        {
            picture: "images/14_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 14,
            expected: "different",
            angle: 150
        },
        {
            picture: "images/15_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 15,
            expected: "same",
            angle: 50
        },
        {
            picture: "images/15_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 15,
            expected: "different",
            angle: 50
        },
        {
            picture: "images/15_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 15,
            expected: "same",
            angle: 150
        },
        {
            picture: "images/15_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 15,
            expected: "different",
            angle: 150
        },
];
const main_trials = [
        {
            picture: "images/1_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 1,
            expected: "same",
            angle: 50,

        },
        {
            picture: "images/1_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 1,
            expected: "different",
            angle: 50,

        },
        {
            picture: "images/1_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 1,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/1_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 1,
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/2_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 2,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/2_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 2,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/2_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 2,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/2_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 2,
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/3_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 3,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/3_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 3,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/3_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 3,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/3_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 3,
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/4_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 4,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/4_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 4,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/4_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 4,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/4_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 4,
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/5_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 5,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/5_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 5,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/5_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 5,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/5_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 5,
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/6_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 6,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/6_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 6,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/6_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 6,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/6_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 6,
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/7_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 7,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/7_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 7,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/7_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 7,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/7_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 7,
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/8_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 8,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/8_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 8,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/8_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 8,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/8_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 8,
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/9_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 9,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/9_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 9,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/9_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 9,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/9_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 9,
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/10_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 10,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/10_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 10,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/10_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 10,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/10_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 10,
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/11_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 11,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/11_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 11,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/11_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 11,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/11_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 11,
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/12_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 12,
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/12_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 12,
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/12_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 12,
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/12_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            item: 12,
            expected: "different",
            angle: 150,
        },
];
